### ISSUE TITLE
Afvalwijzer notification

### ISSUE THREAD

**Issue by bedar89** [sga-noud/adaptive-mushroom#1]
Create code and beautiful dashboards! Thanks again for sharing!
I do like the notification for gft. But I'm using a different integration (recycle) and would like to track other types of garbage as well. I'm interested to know how you would implement multiple types here. I was thinking about 1 notification per type, but on some days I have multiple types at once, so that would generate 2 notifications.

Could you perhaps adapt your code to use multiple types of garbage as well?

p.s. don't mind the recycle integration, I'll try to solve it myself.

**Comment by sga-noud** [comment]
Hi Bedar, why don’t you add notification cards for each garbage type? They are conditional cards, so they will only show when a specific type is due. On some days when multiple types are due at once, it would show multiple cards. 

You could also edit the condition to show a single card when any of the types is due, it would just require a bit more coding. As I only have gft in my area, this is not really applicable to me…

Besides the cards, I do also have an automation that sends a phone notification the night before gft is collected. I’ll upload my automations.yaml soon.

**Comment by bedar89** [comment]
Thank you for your insights! Looking forward to all future updates ;-)
