### ISSUE TITLE
Other views

### ISSUE THREAD

**Issue by Holewijn** [sga-noud/adaptive-mushroom#2]
Hey, i see u have only some of the homepage and devices pages. Could u add other pages also? Or a full copy of your install. I am not the best with codes but i could edit all devices what i do mostly.

This dashboard is working really nice on mobile for my wife 🙏

**Comment by sga-noud** [comment]
Hi Holewijn, I didn’t see your message but by coincidence I just added two pages 😁 About to add the last one now.

Great to hear the dash is working for you!
